name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Run unit tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref == 'main' && github.event.pull_request.base.ref == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.9"

      - name: Terraform Init
        run: terraform init
